# This is a basic workflow to help you get started with Actions

name: Update FinBERT

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Download model
      run: |
        curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
        wget http://dl.turkunlp.org/finbert/torch-transformers/bert-base-finnish-cased-v1/pytorch_model.bin
        wget http://dl.turkunlp.org/finbert/torch-transformers/bert-base-finnish-cased-v1/config.json
        wget http://dl.turkunlp.org/finbert/torch-transformers/bert-base-finnish-cased-v1/vocab.txt
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.1.4
      with:
        commit_message: Refresh model
        branch: ${{ github.head_ref }}


    # Runs a set of commands using the runners shell

    
